---

- name: Ensure psycopg2 is installed
  yum: name=python-psycopg2 state=present

- name: Ensure Postgres is not installed from the default YUM repo
  ini_file: dest=/etc/yum.repos.d/CentOS-Base.repo section="{{ item }}" option="exclude"
            value="postgresql*" backup=yes
  with_items:
    - base
    - updates

- name: Ensure Postgres repository RPM is installed
  yum: name=http://yum.postgresql.org/9.3/redhat/rhel-6-x86_64/pgdg-centos93-9.3-1.noarch.rpm
       state=present

- name: Ensure Postgres and extra packages are installed
  yum: name={{ item }} state=present
  with_items:
    - postgresql93
    - postgresql93-server
    - postgresql93-devel
    - postgresql93-libs
    - postgresql93-contrib

- name: Ensure symlink for pg_config is installed
  file: src=/usr/pgsql-9.3/bin/pg_config dest=/bin/pg_config state=link

- name: Initialize database
  command: service postgresql-9.3 initdb creates=/var/lib/pgsql/9.3/data/postgresql.conf

- name: Update postgresql.conf file
  sudo: yes
  sudo_user: postgres
  template: src=postgresql.conf dest=/var/lib/pgsql/9.3/data/postgresql.conf backup=yes
  notify: restart postgres

- name: Update pg_hba
  sudo: yes
  sudo_user: postgres
  template: src=pg_hba.conf dest=/var/lib/pgsql/9.3/data/pg_hba.conf backup=yes
  notify: restart postgres

- name: Ensure Postgres is started and always starts on boot
  service: name=postgresql-9.3 state=started enabled=yes

- name: Ensure database user exists
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name={{ postgres_db_user }}
    password={{ postgres_db_pass }}
    encrypted={{ postgres_db_pass_encrypted | default(false) }}
  when: postgres_db_user is defined and postgres_db_pass is defined
  notify: restart postgres

- name: Ensure application database exists
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name={{ postgres_db_name }}
    owner={{ postgres_db_user }}
    encoding={{ postgres_db_encoding }}
    lc_collate={{ postgres_db_lc_collate }}
    lc_ctype={{ postgres_db_lc_ctype }}
    template={{ postgres_db_template }}
    state=present
  when: postgres_db_name is defined and postgres_db_user is defined 
        and postgres_db_encoding is defined and postgres_db_lc_collate is defined
        and postgres_db_lc_ctype is defined and postgres_db_template is defined
  notify: restart postgres
